# name: Production Workflow

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     name: CD Pipeline
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: [3.8]
#         node-version: ['12.x']
#         appname: ['event-dapp']
#         deploy-group: ['dev']
#         s3-bucket: ['phoenix-dao-lp-codedeploy']
#         s3-filename: ['phoenix-dao-lp-frontend-${{ github.sha }}']

#     # needs: buildAndTest
#     steps:
#       - uses: actions/checkout@v2

#       # Initialize Node.js
#       - name: Install Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}

#       # Install project dependencies and build
#       - name: Install dependencies
#         run: npm install
#       - name: Run build
#         run: npm run build
#         env:
#           CI: false


#       # Configure AWS credentials
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       # Deploy push to AWS S3
#       - name: AWS Deploy push
#         run: |
#           aws deploy push \
#           --application-name ${{ matrix.appname }} \
#           --description "This is a revision for the ${{ matrix.appname }}-${{ github.sha }}" \
#           --ignore-hidden-files \
#           --s3-location s3://${{ matrix.s3-bucket }}/${{ matrix.s3-filename }}.zip \
#           --source .
#       # Create deployment to CodeDeploy
#       - name: AWS Create Deployment
#         run: |
#           aws deploy create-deployment \
#            --application-name ${{ matrix.appname }} \
#            --deployment-config-name CodeDeployDefault.OneAtATime \
#            --deployment-group-name ${{ matrix.deploy-group }} \
#            --file-exists-behavior OVERWRITE \
#            --s3-location bucket=${{ matrix.s3-bucket }},key=${{ matrix.s3-filename }}.zip,bundleType=zip \
